# Generated by Django 4.2 on 2024-09-03 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wardrobe_manager', '0004_wardrobecategory_wardrobeoccasion_wardrobeoutfit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather_type', models.CharField(max_length=50)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'outfit_recommender_weatherconditions',
            },
        ),
        migrations.CreateModel(
            name='OutfitRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('skin_tone', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendation_type', models.CharField(choices=[('Smart', 'Smart'), ('Preference', 'Preference')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wardrobe_manager.wardrobeoccasion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weather_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outfit_recommender.weatherconditions')),
            ],
            options={
                'db_table': 'outfit_recommender_outfitrecommendations',
            },
        ),
        migrations.CreateModel(
            name='OutfitRecommendationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_by_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_manager.wardrobeoutfit')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfit_recommender.outfitrecommendations')),
            ],
            options={
                'db_table': 'outfit_recommender_outfitrecommendationresults',
            },
        ),
    ]
