# Generated by Django 4.2 on 2024-10-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitrecommendationresults',
            name='outfit',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='outfitrecommendationresults',
            name='recommendation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='outfitrecommendations',
            name='occasion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outfitrecommendations',
            name='recommendation_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outfitrecommendations',
            name='weather_condition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
