# Generated by Django 4.2 on 2024-10-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_recommender', '0002_alter_outfitrecommendationresults_outfit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitrecommendations',
            name='recommendation_image',
            field=models.ImageField(blank=True, null=True, upload_to='outfit_recommendations'),
        ),
    ]
