# Generated by Django 4.2 on 2024-10-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_recommender', '0004_alter_outfitrecommendations_recommendation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitrecommendations',
            name='recommendation_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
