# Generated by Django 4.2 on 2024-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_recommender', '0005_alter_outfitrecommendations_recommendation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitrecommendations',
            name='closet_not_want',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outfitrecommendations',
            name='closet_want',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
