# Generated by Django 4.2 on 2024-10-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.ImageField(blank=True, null=True, upload_to='post_media'),
        ),
    ]
