# Generated by Django 4.2 on 2024-10-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_platform', '0002_alter_post_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_type',
        ),
    ]
