# Generated by Django 4.2 on 2024-10-11 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('processed_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('similarity_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('suitability_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopping_advisor_clothing_recognition',
            },
        ),
        migrations.CreateModel(
            name='RecognitionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('log_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recognition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_advisor.clothingrecognition')),
            ],
            options={
                'db_table': 'shopping_advisor_recognition_logs',
            },
        ),
        migrations.CreateModel(
            name='ClothingComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recognition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_advisor.clothingrecognition')),
                ('wardrobe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_manager.item')),
            ],
            options={
                'db_table': 'shopping_advisor_clothing_comparison',
            },
        ),
    ]
