# Generated by Django 4.2 on 2024-08-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=7)),
                ('skin_color', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
                ('eye_color', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('fitness_problem1', models.CharField(blank=True, max_length=100, null=True)),
                ('fitness_problem2', models.CharField(blank=True, max_length=100, null=True)),
                ('fitness_problem3', models.CharField(blank=True, max_length=100, null=True)),
                ('fitness_problem4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
