# Generated by Django 4.2 on 2024-08-11 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('color_analyzer', '0002_coloranalysis_delete_coloranalysismanage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloranalysis',
            name='season',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=7),
        ),
        migrations.AlterField(
            model_name='coloranalysis',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
