# Generated by Django 4.2 on 2024-09-04 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('color_analyzer', '0002_coloranalysis_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTestOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('color_code', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'color_analyzer_color_test_options',
            },
        ),
        migrations.CreateModel(
            name='ColorTestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('requires_user_image', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'color_analyzer_color_test_questions',
            },
        ),
        migrations.CreateModel(
            name='UserColorTestAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color_analyzer.colortestquestions')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color_analyzer.colortestoptions')),
            ],
            options={
                'db_table': 'color_analyzer_user_color_test_answers',
            },
        ),
        migrations.CreateModel(
            name='UserColorTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_type', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'color_analyzer_user_color_tests',
            },
        ),
        migrations.DeleteModel(
            name='ColorAnalysis',
        ),
        migrations.AddField(
            model_name='usercolortestanswers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color_analyzer.usercolortests'),
        ),
        migrations.AddField(
            model_name='colortestoptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color_analyzer.colortestquestions'),
        ),
    ]
