# Generated by Django 4.2 on 2024-10-26 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('color_analyzer', '0003_colortestoptions_colortestquestions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserColorTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='color_tests/')),
                ('result_type', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=10)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_color_tests',
            },
        ),
        migrations.RemoveField(
            model_name='usercolortestanswers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='usercolortestanswers',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='usercolortestanswers',
            name='test',
        ),
        migrations.RemoveField(
            model_name='usercolortests',
            name='user',
        ),
        migrations.DeleteModel(
            name='ColorTestOptions',
        ),
        migrations.DeleteModel(
            name='ColorTestQuestions',
        ),
        migrations.DeleteModel(
            name='UserColorTestAnswers',
        ),
        migrations.DeleteModel(
            name='UserColorTests',
        ),
    ]
