# Generated by Django 4.2 on 2024-08-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_analyzer', '0003_alter_coloranalysis_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloranalysis',
            name='fitness_problem1',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='coloranalysis',
            name='fitness_problem2',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='coloranalysis',
            name='fitness_problem3',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='coloranalysis',
            name='fitness_problem4',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
