# Generated by Django 4.2 on 2024-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_analyzer', '0004_coloranalysis_fitness_problem1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloranalysis',
            name='fitness_problem1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coloranalysis',
            name='fitness_problem2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coloranalysis',
            name='fitness_problem3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coloranalysis',
            name='fitness_problem4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
