# Generated by Django 4.2 on 2024-10-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_analyzer', '0004_usercolortest_remove_usercolortestanswers_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercolortest',
            name='test_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
