# Generated by Django 4.2 on 2024-10-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_analyzer', '0005_usercolortest_test_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercolortest',
            options={'ordering': ['-test_date']},
        ),
        migrations.AlterField(
            model_name='usercolortest',
            name='test_name',
            field=models.CharField(default='未命名測驗', max_length=50),
        ),
    ]
