# Generated by Django 4.2 on 2024-10-11 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe_manager', '0001_initial'),
        ('member', '0003_userauthprovider_last_login_alter_user_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='outfit_scheduler_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('linebot_notify_time', models.TimeField(blank=True, null=True)),
                ('google_calendar_sync', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'outfit_scheduler_user_preferences',
            },
        ),
        migrations.CreateModel(
            name='OutfitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_manager.outfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outfit_scheduler_outfit_schedule',
            },
        ),
        migrations.CreateModel(
            name='EventLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('log_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfit_scheduler.outfitschedule')),
            ],
            options={
                'db_table': 'outfit_scheduler_event_logs',
            },
        ),
    ]
