# Generated by Django 4.2 on 2024-09-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventlogs',
            table='outfit_scheduler_event_logs',
        ),
        migrations.AlterModelTable(
            name='outfitschedule',
            table='outfit_scheduler_outfit_schedule',
        ),
        migrations.AlterModelTable(
            name='userpreferences',
            table='outfit_scheduler_user_preferences',
        ),
    ]
