# Generated by Django 4.2 on 2024-08-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleOAuthToken',
        ),
    ]
