# Generated by Django 4.2 on 2024-10-24 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_user_uuid_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauthprovider',
            options={'verbose_name': 'User Authentication Provider', 'verbose_name_plural': 'User Authentication Providers'},
        ),
        migrations.AlterField(
            model_name='userauthprovider',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userauthprovider',
            name='provider_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
