# Generated by Django 4.2 on 2024-10-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_userauthprovider_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuthProvider',
        ),
    ]
