# Generated by Django 4.2 on 2024-07-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='garbage_can',
            field=models.BooleanField(default=False),
        ),
    ]
