# Generated by Django 4.2 on 2024-08-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_manager', '0002_wardrobeitem_garbage_can'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='user_id',
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='tags',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
