# Generated by Django 4.2 on 2024-10-13 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_manager', '0002_clothsubcategory_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
