# Generated by Django 4.2 on 2024-10-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_manager', '0003_item_add_date_item_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='occasions',
            field=models.ManyToManyField(related_name='items', through='wardrobe_manager.ItemOccasion', to='wardrobe_manager.occasion'),
        ),
    ]
