# Generated by Django 4.2 on 2024-08-30 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wardrobe_manager', '0003_remove_wardrobeitem_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latest_edit', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='wardrobeitem',
            old_name='item_type',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='wardrobeitem',
            old_name='garbage_can',
            new_name='is_in_trash',
        ),
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='tags',
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='latest_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='item_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='WardrobeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('temperature', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_manager.wardrobecategory')),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeOutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_manager.wardrobeitem')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_manager.wardrobeoutfit')),
            ],
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wardrobe_manager.wardrobetype'),
        ),
        migrations.CreateModel(
            name='WardrobeOutfitOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_manager.wardrobeoccasion')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_manager.wardrobeoutfit')),
            ],
            options={
                'unique_together': {('outfit', 'occasion')},
            },
        ),
        migrations.CreateModel(
            name='WardrobeItemOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_manager.wardrobeitem')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe_manager.wardrobeoccasion')),
            ],
            options={
                'unique_together': {('item', 'occasion')},
            },
        ),
    ]
