# Generated by Django 4.2 on 2024-09-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_manager', '0004_wardrobecategory_wardrobeoccasion_wardrobeoutfit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='Label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
