# Generated by Django 4.2 on 2024-10-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_manager', '0004_item_occasions'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_in_love',
            field=models.BooleanField(default=False),
        ),
    ]
